spring:
  datasource:
    url: jdbc:mysql://118.31.12.175:3306/poets?serverTimezone=UTC
    #url: jdbc:mysql://localhost:3306/poet?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 118.31.12.175
    port: 6379  #可不配，因为底层默认值为6379
  #spring.resources.static-locations=classpath:/
mybatis:
  typeAliasesPackage: com.poets.dao
  mapperLocations: classpath:mappers/*.xml

upload:
  qiniu:
    domain: q6pn1p8cf.bkt.clouddn.com
    access-key: U7iuJHsq5knZMU22Bd8JR11GpOcS7Z0i4ma3n5RM
    secret-key: IsRk8WjvituvSf6eER2HcxGgAPgJIlw2rP-Ld-pU
    bucket: bearchu

server:
  port: 8081
  session:
    timeout:
      7200



